### ISSUE TITLE
Install script raising an error.

### ISSUE THREAD

**Issue by myermo** [JustWhit3/osmanip#8]
Executing ```./scripts/install.sh``` raises the following error:

Doctest is not installed, cannot compile the test codes!

./scripts/install.sh: line 22: eco: order not found.
make: *** No rule to make target `bin/main'. Stop.
Compilation failed!

I'm opening the issue because in the documentation it is stated that Doctest is optional.

**Comment by JustWhit3** [comment]
Hi @myermo yes, Doctest installation is optional. The first output string:

`Doctest is not installed, cannot compile the test codes!`

tells you that ONLY test codes are not compiled, but source code should be ok until that point.

The next compilation issue is due to the fact that I accidentally deleted a word from the `echo` command, during the last update. Now it has been restored with commit [8c62805](https://github.com/JustWhit3/osmanip/commit/8d4da4d2837634312ea80d92a8b1e569c81a633a)  and should correctly work.

Thanks a lot for reporting this bug.

@all-contributors please add @myermo for review

**Comment by myermo** [comment]
Hello @JustWhit3. Thanks for the quick fix.

The script is still not compiling:

```make: *** No rule to make target `bin/main'. Stop.```

**Comment by myermo** [comment]
Yes, I am doing exactly that.

**Comment by JustWhit3** [comment]
In which operating system are you running?

**Comment by myermo** [comment]
Hi,

`uname -a`
`Linux manjaro-PC 5.13.19-2-MANJARO #1 SMP PREEMPT Sun Sep 19 21:31:53 UTC 2021 x86_64 GNU/Linux`

`ls`
`CITATION.cff doc img include  LICENSE  makefile  obj  README.md  scripts  src  test`

`./scripts/install.sh`
`Doctest is not installed, cannot compile the test codes!
Compiling only the main code (this is not a problem for the installation)...
make: *** No rule to make target "bin/main". Stop.
Compilation failed!
`

**Comment by JustWhit3** [comment]
Ok, with commits [186bf5a](https://github.com/JustWhit3/osmanip/commit/186bf5a6799e21f49bd0b637af0b79250b8a0652) , [f1606a8](https://github.com/JustWhit3/osmanip/commit/f1606a812178bce06a080b1a247898bf62f4b92b) and [207385b](https://github.com/JustWhit3/osmanip/commit/207385b22c9c684ac8ff87b65fc62be297b5c5be) the bug should have been fixed. I tested it on both Ubuntu and WSL operating systems. I also updated the [documentation](https://github.com/JustWhit3/osmanip/blob/main/doc/Download%20and%20install.md#:~:text=the%20library%20features.-,Compile%20the%20source%20code%20example%20and%20testing,-The%20source%20code), but nothing changed for the installation: you can simply update the repository and launch the installation command again. 

Let me know if now is ok.

**Comment by myermo** [comment]
It's working properly now. Thanks!
